# coding: utf-8
from goldminer.models.models import BalanceSheet
from goldminer.spider.v3.BaseFundamentalSpider import BaseFundamentalSpider


class StockBalanceSheetSpider(BaseFundamentalSpider):

    def __init__(self):
        super(StockBalanceSheetSpider, self).__init__()
        self.modelClass = BalanceSheet
        self.table = 'balance_sheet'
        self.fields = 'ACCHELDFORS,ACCOPAYA,ACCORECE,ACCREXPE,ACCUDEPR,ACTITRADSECU,ACTIUNDESECU,ADVAPAYM,AVAISELLASSE,BDSPAYA,BDSPAYAPERBOND,BDSPAYAPREST,CAPISURP,CENBANKBORR,COMASSE,CONSPROG,COPEPOUN,COPEWITHREINRECE,COPEWORKERSAL,CURFDS,CURTRANDIFF,DEFEINCOTAXLIAB,DEFEREVE,DEFETAXASSET,DEPOSIT,DERIFINAASSET,DERILIAB,DEVEEXPE,DIVIDRECE,DIVIPAYA,DOMETICKSETT,DUENONCLIAB,ENGIMATE,EQUIINVE,EXPECURRLIAB,EXPENONCLIAB,EXPINONCURRASSET,EXPOTAXREBARECE,FDSBORR,FIXEDASSECLEA,FIXEDASSEIMMO,FIXEDASSEIMPA,FIXEDASSENET,FIXEDASSENETW,GENERISKRESE,GOODWILL,HOLDINVEDUE,HYDRASSET,INSUCONTRESE,INTAASSET,INTELPAY,INTELRECE,INTEPAYA,INTERECE,INTETICKSETT,INVE,INVEPROP,LCOPEWORKERSAL,LENDANDLOAN,LIABHELDFORS,LOGPREPEXPE,LONGBORR,LONGDEFEINCO,LONGPAYA,LONGRECE,MARGRECE,MARGREQU,MINYSHARRIGH,NOTESPAYA,NOTESRECE,OCL,OTHEQUIN,OTHERCURRASSE,OTHERCURRELIABI,OTHERFEEPAYA,OTHERLONGINVE,OTHERNONCASSE,OTHERNONCLIABI,OTHERPAY,OTHERRECE,PAIDINCAPI,PARESHARRIGH,PERBOND,PLAC,PREMRECE,PREP,PREPEXPE,PREST,PRODASSE,PUBLISHDATE,PURCRESAASSET,REINCONTRESE,REINRECE,RESE,RIGHAGGR,SELLREPASSE,SETTRESEDEPO,SFORMATCURRASSE,SFORMATCURRELIABI,SFORMATNONCASSE,SFORMATNONCLIAB,SFORMATPARESHARRIGH,SFORMATRIGHAGGR,SFORMATTOTASSET,SFORMATTOTLIAB,SFORMATTOTLIABSHAREQUI,SHORTTERMBDSPAYA,SHORTTERMBORR,SMERGERCURRASSE,SMERGERCURRELIABI,SMERGERNONCASSE,SMERGERNONCLIAB,SMERGERPARESHARRIGH,SMERGERRIGHAGGR,SMERGERTOTASSET,SMERGERTOTLIAB,SMERGERTOTLIABSHAREQUI,SPECPAYA,SPECRESE,SUBSRECE,SUNEVENASSETLIABEUQI,SUNEVENCURRASSE,SUNEVENCURRELIABI,SUNEVENNONCASSE,SUNEVENNONCLIAB,SUNEVENPARESHARRIGH,SUNEVENRIGHAGGR,SUNEVENTOTASSET,SUNEVENTOTLIAB,SUNEVENTOTLIABSHAREQUI,TAXESPAYA,TOPAYCASHDIVI,TOTALCURRLIAB,TOTALNONCASSETS,TOTALNONCLIAB,TOTASSET,TOTCURRASSET,TOTLIAB,TOTLIABSHAREQUI,TRADFINASSET,TRADFINLIAB,TRADSHARTRAD,TREASTK,UNDIPROF,UNREINVELOSS,UNSEG,WARLIABRESE'


if __name__ == "__main__":
    spider = StockBalanceSheetSpider()
    spider.downloadByCode('000001')
