# coding: utf-8

from goldminer.models import IncomeStatement
from goldminer.spider.v3.BaseFundamentalSpider import BaseFundamentalSpider


class StockIncomeStatementSpider(BaseFundamentalSpider):

    def __init__(self):
        super(StockIncomeStatementSpider, self).__init__()
        self.modelClass = IncomeStatement
        self.table = 'income_statement'
        self.fields = 'ASSEIMPALOSS,ASSOINVEPROF,AVAIDISTPROF,AVAIDISTSHAREPROF,BASICEPS,BIZCOST,BIZINCO,BIZTAX,BIZTOTCOST,BIZTOTINCO,CINAFORSFV,CINALIBOFRBP,COMDIVPAYBABLE,COMPCODE,COMPINCOAMT,COMPNETEXPE,CONTRESS,CPLTOHINCO,CUSTINCO,DEVEEXPE,DILUTEDEPS,EARLYUNDIPROF,EARNPREM,EPOCFHGL,EQUMCPOTHINCO,EUQMICOLOTHINCO,EXCHGGAIN,EXTRARBIRESE,EXTSTAFFFUND,FINEXPE,FUTULOSS,HTMCCINAFORSFV,INCOTAXEXPE,INTEEXPE,INTEINCO,INVEINCO,LEGALSURP,MAINBIZCOST,MAINBIZINCO,MANAEXPE,MERGEFORMNETPROF,MINYSHARINCO,MINYSHARINCOAMT,MINYSHARRIGH,NCPOTHINCO,NETPROFIT,NONCASSETSDISI,NONCASSETSDISL,NONOEXPE,NONOREVE,OTHERBIZCOST,OTHERBIZINCO,OTHERBIZPROF,OTHERCOMPINCO,OTHERCPLTOHINCO,OTHERREASADJU,PARECOMPINCO,PARECOMPINCOAMT,PARENETP,PERPROFIT,PEXTCCAPIFD,PEXTCDEVEFD,POLIDIVIEXPE,POUNEXPE,POUNINCO,PPROFRETUINVE,PREFSTOCKDIVI,PSUPPFLOWCAPI,PUBLISHDATE,REALSALE,REALSALECOST,REINEXPE,RUNDISPROBYRREGCAP,SALESEXPE,SFORMATAVAIDISTPROF,SFORMATAVAIDISTSHAREPROF,SFORMATBIZTOTCOST,SFORMATBIZTOTINCO,SFORMATNETPROFIT,SFORMATNETPROFITSUB,SFORMATPERPROFIT,SFORMATTOTPROFIT,SFORMATUNDIPROF,SMERGERAVAIDISTPROF,SMERGERAVAIDISTSHAREPROF,SMERGERBIZTOTCOST,SMERGERBIZTOTINCO,SMERGERCOMPINCOAMTSUB,SMERGERNETPROFIT,SMERGERNETPROFITSUB,SMERGERPERPROFIT,SMERGERTOTPROFIT,SMERGERUNDIPROF,STATEXTRUNDI,SUBSIDYINCOME,SUNEVENAVAIDISTPROF,SUNEVENAVAIDISTSHAREPROF,SUNEVENBIZTOTCOST,SUNEVENBIZTOTINCO,SUNEVENCOMPINCOAMT,SUNEVENCOMPINCOAMTSUB,SUNEVENNETPROFIT,SUNEVENNETPROFITSUB,SUNEVENOTHCOMPINCOAMT,SUNEVENPERPROFIT,SUNEVENTOTPROFIT,SUNEVENUNDIPROF,SURRGOLD,TDIFFFORCUR,TOTPROFIT,TRUSTLOSS,TURNCAPSDIVI,UNDIPROF,UNREINVELOSS,VALUECHGLOSS'


if __name__ == "__main__":
    spider = StockIncomeStatementSpider()
    spider.downloadByCode('000001')
