
# coding: utf-8

# In[ ]:


# coding=utf-8
from __future__ import absolute_import, print_function, unicode_literals

import sys

from gm.api import *

sys.path.append('../')
from storage.DB import *
from StockManager import *
from IndexManager import *
from FundamentalsManager import *

set_token('a0998908534d317105b2184afbe436a4104dc51b')

fieldstr = 'ACCHELDFORS,ACCOPAYA,ACCORECE,ACCREXPE,ACCUDEPR,ACTITRADSECU,ACTIUNDESECU,ADVAPAYM,AVAISELLASSE,BDSPAYA,BDSPAYAPERBOND,BDSPAYAPREST,CAPISURP,CENBANKBORR,COMASSE,CONSPROG,COPEPOUN,COPEWITHREINRECE,COPEWORKERSAL,CURFDS,CURTRANDIFF,DEFEINCOTAXLIAB,DEFEREVE,DEFETAXASSET,DEPOSIT,DERIFINAASSET,DERILIAB,DEVEEXPE,DIVIDRECE,DIVIPAYA,DOMETICKSETT,DUENONCLIAB,ENGIMATE,EQUIINVE,EXPECURRLIAB,EXPENONCLIAB,EXPINONCURRASSET,EXPOTAXREBARECE,FDSBORR,FIXEDASSECLEA,FIXEDASSEIMMO,FIXEDASSEIMPA,FIXEDASSENET,FIXEDASSENETW,GENERISKRESE,GOODWILL,HOLDINVEDUE,HYDRASSET,INSUCONTRESE,INTAASSET,INTELPAY,INTELRECE,INTEPAYA,INTERECE,INTETICKSETT,INVE,INVEPROP,LCOPEWORKERSAL,LENDANDLOAN,LIABHELDFORS,LOGPREPEXPE,LONGBORR,LONGDEFEINCO,LONGPAYA,LONGRECE,MARGRECE,MARGREQU,MINYSHARRIGH,NOTESPAYA,NOTESRECE,OCL,OTHEQUIN,OTHERCURRASSE,OTHERCURRELIABI,OTHERFEEPAYA,OTHERLONGINVE,OTHERNONCASSE,OTHERNONCLIABI,OTHERPAY,OTHERRECE,PAIDINCAPI,PARESHARRIGH,PERBOND,PLAC,PREMRECE,PREP,PREPEXPE,PREST,PRODASSE,PUBLISHDATE,PURCRESAASSET,REINCONTRESE,REINRECE,RESE,RIGHAGGR,SELLREPASSE,SETTRESEDEPO,SFORMATCURRASSE,SFORMATCURRELIABI,SFORMATNONCASSE,SFORMATNONCLIAB,SFORMATPARESHARRIGH,SFORMATRIGHAGGR,SFORMATTOTASSET,SFORMATTOTLIAB,SFORMATTOTLIABSHAREQUI,SHORTTERMBDSPAYA,SHORTTERMBORR,SMERGERCURRASSE,SMERGERCURRELIABI,SMERGERNONCASSE,SMERGERNONCLIAB,SMERGERPARESHARRIGH,SMERGERRIGHAGGR,SMERGERTOTASSET,SMERGERTOTLIAB,SMERGERTOTLIABSHAREQUI,SPECPAYA,SPECRESE,SUBSRECE,SUNEVENASSETLIABEUQI,SUNEVENCURRASSE,SUNEVENCURRELIABI,SUNEVENNONCASSE,SUNEVENNONCLIAB,SUNEVENPARESHARRIGH,SUNEVENRIGHAGGR,SUNEVENTOTASSET,SUNEVENTOTLIAB,SUNEVENTOTLIABSHAREQUI,TAXESPAYA,TOPAYCASHDIVI,TOTALCURRLIAB,TOTALNONCASSETS,TOTALNONCLIAB,TOTASSET,TOTCURRASSET,TOTLIAB,TOTLIABSHAREQUI,TRADFINASSET,TRADFINLIAB,TRADSHARTRAD,TREASTK,UNDIPROF,UNREINVELOSS,UNSEG,WARLIABRESE'
table = 'balance_sheet'
providor = FundamentalsManager()
stockData = StockManager()

for code in stockData.getStockList():
    print("##", code, "##")
    fundamentals = providor.getFundamentals(code, table, fieldstr)
    providor.saveFundamentals(code, fundamentals, table, fieldstr)
    time.sleep(0.1)
