#!/usr/bin/python
# coding: utf-8
from goldminer.indicators.EPSScoreProcessor import EPSScoreProcessor
from goldminer.indicators.IndexPEPBGenerator import IndexPEPBGenerator
from goldminer.indicators.NDayGainsProcessor import NDayGainsProcessor
from goldminer.indicators.RPSProcessor import RPSProcessor
from goldminer.investigation.buy_signals.pivot_point.PivotPoint import PivotPoint

eps = EPSScoreProcessor()
eps.processAll()

pepbGenerator = IndexPEPBGenerator()
pepbGenerator.updateAll()

processor = NDayGainsProcessor()
processor.updateAll()

rps = RPSProcessor()
rps.buildAll()

processor = PivotPoint()
processor.processAll()