#!/usr/bin/python
# coding: utf-8
from goldminer.spider.tushare.IndexSpider import IndexSpider
from goldminer.spider.tushare.StockSpider import StockSpider
from goldminer.spider.v3.IndexBarSpider import IndexBarSpider
from goldminer.spider.v3.IndexWeightsSpider import IndexWeightsSpider
from goldminer.spider.v3.StockBalanceSheetSpider import StockBalanceSheetSpider
from goldminer.spider.v3.StockDailyBarAdjustNoneSpider import StockDailyBarAdjustNoneSpider
from goldminer.spider.v3.StockDailyBarAdjustPrevSpider import StockDailyBarAdjustPrevSpider
from goldminer.spider.v3.StockDerivativeFinanceIndicatorSpider import StockDerivativeFinanceIndicatorSpider
from goldminer.spider.v3.StockIncomeStatementSpider import StockIncomeStatementSpider
from goldminer.spider.v3.StockIndustrySpider import StockIndustrySpider
from goldminer.spider.v3.StockPrimaryFinanceIndicatorSpider import StockPrimaryFinanceIndicatorSpider
from goldminer.spider.v3.StockTradingDerivativeIndicatorSpider import StockTradingDerivativeIndicatorSpider


'''
Download newest stock list
'''
spider = StockSpider()
spider.getStockFromTuShare()


'''
Update stock industry from goldminer
'''

spider = StockIndustrySpider()
spider.updateIndustry()

spider = IndexSpider()
spider.updateIndexListFromTushare()


'''
Download all index weights
'''
spider = IndexWeightsSpider()
spider.downloadAllIndexConstituents()


'''
Download all index bars
'''
spider = IndexBarSpider()
spider.downloadAllIndexBars()


'''
Download all stock bars with no adjustment
'''
spider = StockDailyBarAdjustNoneSpider()
spider.downloadAll()


# '''
# Download all stock bars with prev adjustment
# '''
# spider = StockDailyBarAdjustPrevSpider()
# spider.downloadAll()


'''
Download Balance Sheet
'''
spider = StockBalanceSheetSpider()
spider.downloadAll(mode="batch", batch_size=40)

'''
Download Income Statement
'''
spider = StockIncomeStatementSpider()
spider.downloadAll(mode="batch", batch_size=40)

'''
Download Primary Finance Indicator
'''
spider = StockPrimaryFinanceIndicatorSpider()
spider.downloadAll(mode="batch", batch_size=40)

'''
Download Trading Derivative Indicator
'''
spider = StockTradingDerivativeIndicatorSpider()
spider.downloadAll(mode="single")

'''
Download Derivative Finance Indicator
'''
spider = StockDerivativeFinanceIndicatorSpider()
spider.downloadAll(mode="batch", batch_size=40)
