#!/usr/bin/python
# coding: utf-8

from goldminer.indicators.IndexPEPBGenerator import IndexPEPBGenerator
from goldminer.indicators.RPSProcessor import RPSProcessor

pepbGenerator = IndexPEPBGenerator()
pepbGenerator.updateAll()


rps = RPSProcessor()
rps.buildLastWeek()
